export const estados = [
    { nome: "Acre", uf: "AC" },
    { nome: "Alagoas", uf: "AL" },
    { nome: "Amapá", uf: "AP" },
    { nome: "Amazonas", uf: "AM" },
    { nome: "Bahia", uf: "BA" },
    { nome: "Ceará", uf: "CE" },
    { nome: "Distrito Federal", uf: "DF" },
    { nome: "Espírito Santo", uf: "ES" },
    { nome: "Goiás", uf: "GO" },
    { nome: "Maranhão", uf: "MA" },
    { nome: "Minas Gerais", uf: "MG" },
    { nome: "Mato Grosso do Sul", uf: "MS" },
    { nome: "Mato Grosso", uf: "MT" },
    { nome: "Pará", uf: "PA" },
    { nome: "Paraíba", uf: "PB" },
    { nome: "Pernambuco", uf: "PE" },
    { nome: "Piauí", uf: "PI" },
    { nome: "Paraná", uf: "PR" },
    { nome: "Rio de Janeiro", uf: "RJ" },
    { nome: "Rio Grande do Norte", uf: "RN" },
    { nome: "Rondônia", uf: "RO" },
    { nome: "Roraima", uf: "RR" },
    { nome: "Rio Grande do Sul", uf: "RS" },
    { nome: "Santa Catarina", uf: "SC" },
    { nome: "Sergipe", uf: "SE" },
    { nome: "São Paulo", uf: "SP" },
    { nome: "Tocantins", uf: "TO" }
];

export const municipios = [
    { nome: "Amapá" },
    { nome: "Calçoene" },
    { nome: "Cutias" },
    { nome: "Ferreira Gomes" },
    { nome: "Itaubal" },
    { nome: "Laranjal do Jari" },
    { nome: "Macapá" },
    { nome: "Mazagão" },
    { nome: "Oiapoque" },
    { nome: "Pedra Branca do Amapari" },
    { nome: "Porto Grande" },
    { nome: "Pracuúba" },
    { nome: "Santana" },
    { nome: "Serra do Navio" },
    { nome: "Tartarugalzinho" },
    { nome: "Vitória do Jari" }
]
